# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://dpo.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Dominique Orban

# Short description of your site
description: Computational Mathematician

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Research: "aboutme"
  Publications: "publications"
  Teaching: "teaching"
  Software: "software"
  Datasets: "datasets"
  GERAD: "https://gerad.ca/en/people/dominique-orban"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: ""

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Dominique Orban
  email: "dominique.orban@gmail.com"
  github: dpo
  googlescholar: OCFgRysAAAAJ
  researchgate: Dominique_Orban
  linkedin: in/dominique-orban-9497ab6
  stackoverflow: 505285/dominique

# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: false
  email: true
  twitter: false
  github: true
  googlescholar: true
  researchgate: true
  linkedin: true
  stackoverflow: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "MyWebsite.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending

  group_by: type
  # type_order: article, inproceeding, techreport
  # group_order: ascending

  source: ./_bibliography
  # bibliography: articles2015.bib
  bibliography_template: bibtemplate

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  # - superscript
  - latexmarkup  # defined in _plugins/ext.rb
  # - markdown  # for \href{...} directives in entries, messes up other things
  - latex
  - doi  # defined in _plugins/ext.rb

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
